title: Summer School in Advanced Spatial Modelling
logo: /assets/img/casa_logo.png
description: The official page.
show_downloads: true
google_analytics: 
theme: jekyll-theme-minimal
repository: henry/henrydf.github.io
plugins_dir:
  - jekyll-seo-tag